ADA1-4
KitBolourchi/AgentDiscoveriesApp-Java pull request #5
Opened 2022-10-06 11:06 UTC by ch55secake

Please review

2022-10-06 16:23 UTC, ch55secake commented on AgentDiscoveries-Frontend/app/sass/styles.scss
> +.aTable {
No its does nothing, something I tried whilst trying to fix a bug feel free to delete it within resolution

2022-10-07 08:23 UTC, RogVan requested changes

2022-10-07 08:23 UTC, RogVan commented on AgentDiscoveries-Backend/src/main/java/org/softwire/training/api/routes/v1/LocationsRoutes.java
> +
Same deal here - extra line

2022-10-07 08:23 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/components/admin/entity.jsx
> +            <tr style={{minWidth: '400px'}} key={this.id}>
We might not need this anymore now we have the fix below

2022-10-07 08:23 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/components/admin/entity.jsx
> +
Extra new line here

2022-10-07 08:23 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/components/admin/location-form.jsx
Probably get rid of these spare lines

2022-10-07 09:27 UTC, merged