Gabriel2
KitBolourchi/AgentDiscoveriesApp-Java pull request #7
Opened 2022-10-06 13:04 UTC by GabrielParle

2022-10-06 14:15 UTC, Wh1rr reviewed
dont really know frontend but seems all good

2022-10-06 14:15 UTC, Wh1rr commented on AgentDiscoveries-Frontend/package-lock.json
> +    "@babel/runtime-corejs2": {
what.

2022-10-06 14:15 UTC, Wh1rr commented on AgentDiscoveries-Frontend/package-lock.json
> +      "integrity": "sha512-jMBt6pUrKn5I+OGgtQ4YZLdhIeJmObddh6CsibPxyQ5yPZm1XExSyzC1LCNX7BzhxWgiHmizBWJTHJIjMjTQYQ==",
why.

2022-10-06 14:15 UTC, Wh1rr commented on AgentDiscoveries-Frontend/app/src/components/home.jsx
> +//import { reactComponent as Bond } from '../../static/james-bond-007.svg';
rip james

2022-10-07 08:30 UTC, RogVan requested changes
Nice, looks really good! Just a couple of small things to tidy up the code.

Make sure to delete any of the image files you aren't planning on using, as they can quickly make the repo really big

2022-10-07 08:30 UTC, RogVan commented on AgentDiscoveries-Backend/src/main/resources/config.properties
> +database.password = root
Do we want to commit these?

2022-10-07 08:30 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/components/home.jsx
> +//import { Redirect } from 'react-router-dom';
Remember to delete comments if you aren't using them

2022-10-07 08:30 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/components/home.jsx
> +
Probably don't need all the whitespace lines in this file, one separating line at most is the usual policy

2022-10-07 08:30 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/components/home.jsx
> +
Same deal with the spare lines here

2022-10-07 08:30 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/components/page.jsx
> +
Lines again here

2022-10-07 08:30 UTC, RogVan commented on AgentDiscoveries-Frontend/app/src/index.jsx
> +
And here

2022-10-07 09:26 UTC, closed without merging